### ISSUE TITLE
CI plugin test error

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_text_blocks#16]
**Problem**
CI plugin test fails, when creating PR.

**To Reproduce**
Any commits fail, like the following DUMMY PR.
https://github.com/gtt-project/redmine_text_blocks/actions/runs/1025422864

**Expectation**
CI tests should be pass.

**Comment by dkastl** [comment]
I disabled it for now.

**Comment by sanak** [comment]
Well, I am thinking to replace [current](https://github.com/gtt-project/redmine_text_blocks/blob/main/.github/workflows/redmine.yml) No.1 way to either of No.2~6 way.
1. https://github.com/two-pack/redmine-plugin-test-action
    * https://github.com/two-pack/redmine_xlsx_format_issue_exporter/tree/master/.github/workflows/ci.yml
2. https://github.com/nanego/redmine_datetime_custom_field/tree/master/.github/workflows
3. https://github.com/clear-code/redmine_full_text_search/blob/master/.github/workflows/test.yml
4. https://github.com/haru/redmine_theme_changer/blob/develop/.github/workflows/build.yml
5. https://github.com/cat-in-136/redmine_scheduling_poll/blob/master/.github/workflows/redmine_plugin.yml
6. https://github.com/AlphaNodes/redmine_sudo/blob/main/.github/workflows/tests.yml
