### ISSUE TITLE
Wikitoolbar shows no preview

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_text_blocks#35]
**Problem**

It seems the "Preview" of the wikitoolbar editor is not working, because it returnes `undefined`.

**To Reproduce**

Create a new text block, write some content into the `Text` field and switch to `Preview`.

**Screenshots**

![image](https://github.com/gtt-project/redmine_text_blocks/assets/227762/67afb41b-47bf-4629-9d66-5140e5340f89)

**Comment by sanak** [comment]
Thanks for finding the issue.
I will take a look at this, later.

**Comment by dkastl** [comment]
Actually I found this when working on another plugin

**Comment by sanak** [comment]
Close this as completed.
